import { FamilyProfile, GovernmentScheme, HealthcareFacility, HealthTwinMetrics } from "./types";

export const DEMO_FAMILIES: FamilyProfile[] = [
  {
    id: "fam-gowda-01",
    familyName: "The Gowda Household",
    village: "Keragodu Village",
    district: "Mandya",
    state: "Karnataka",
    headOfHousehold: "Ramesh Gowda",
    rationCategory: "BPL",
    members: [
      {
        id: "mem-ramesh",
        name: "Ramesh Gowda",
        relation: "Self",
        age: 48,
        gender: "Male",
        village: "Keragodu",
        district: "Mandya",
        state: "Karnataka",
        aadhaarNumber: "7842 9012 4431",
        rationCardNumber: "KA-MAN-BPL-88912",
        annualIncome: 65000,
        healthConditions: ["Pre-hypertension", "Chronic back ache"],
        documents: [
          {
            id: "doc-aadhaar-ramesh",
            type: "aadhaar",
            title: "Aadhaar Card",
            issuingAuthority: "UIDAI (Govt of India)",
            documentNumber: "XXXX-XXXX-4431",
            status: "ready",
            statusLabel: "Verified Demographic Baseline",
            fields: [
              { label: "Full Name", value: "Ramesh Gowda", verified: true },
              { label: "Date of Birth", value: "14/08/1976", verified: true },
              { label: "Gender", value: "Male", verified: true },
              { label: "Address", value: "House No 42, Keragodu, Mandya - 571446", verified: true },
            ],
          },
          {
            id: "doc-ration-ramesh",
            type: "ration",
            title: "BPL Ration Card (Ahara)",
            issuingAuthority: "Food & Civil Supplies Dept, Karnataka",
            documentNumber: "KA-MAN-BPL-88912",
            status: "warning",
            statusLabel: "Name Mismatch Warning",
            issueReason: "Name on Ration Card reads 'Ramesh G.' instead of 'Ramesh Gowda' as printed on Aadhaar Card.",
            fixGuidance: "Submit Form 4 (Aadhaar Seeding / Name Correction) at Grama One / Karnataka-One / CSC center with original Aadhaar copy.",
            fields: [
              { label: "Head Name", value: "Ramesh G.", verified: false, mismatchNote: "Abbreviated last name causes biometric deduplication failure" },
              { label: "Card Type", value: "BPL (Priority Household)", verified: true },
              { label: "FPS Code", value: "FPS-MANDYA-041", verified: true },
            ],
          },
          {
            id: "doc-income-ramesh",
            type: "income",
            title: "Income Certificate (Form F)",
            issuingAuthority: "Revenue Dept, Taluk Tehsildar Mandya",
            documentNumber: "RD-0038819283-INC",
            status: "risk",
            statusLabel: "Certificate Validity Expired",
            issueReason: "Income certificate was issued on 12/03/2023 and expired after 1 year. Needs renewal for PM-JAY scheme verification.",
            fixGuidance: "Apply for instant digital renewal of Income Certificate via Nadakacheri portal or local Grama One kiosk.",
            fields: [
              { label: "Annual Income", value: "₹ 65,000 / year", verified: true },
              { label: "Issue Date", value: "12/03/2023", verified: false, mismatchNote: "Expired > 12 months ago" },
              { label: "Authority Stamp", value: "Mandya Taluk Tehsildar", verified: true },
            ],
          },
        ],
      },
      {
        id: "mem-lakshmi",
        name: "Lakshmi Gowda",
        relation: "Spouse",
        age: 44,
        gender: "Female",
        village: "Keragodu",
        district: "Mandya",
        state: "Karnataka",
        aadhaarNumber: "7842 9012 4432",
        rationCardNumber: "KA-MAN-BPL-88912",
        annualIncome: 0,
        healthConditions: ["Hypertension (Grade 1)", "Mild Anemia"],
        documents: [],
      },
      {
        id: "mem-chethan",
        name: "Chethan Gowda",
        relation: "Child",
        age: 19,
        gender: "Male",
        village: "Keragodu",
        district: "Mandya",
        state: "Karnataka",
        aadhaarNumber: "7842 9012 4433",
        rationCardNumber: "KA-MAN-BPL-88912",
        annualIncome: 0,
        healthConditions: [],
        documents: [],
      },
    ],
  },
  {
    id: "fam-devi-02",
    familyName: "The Devi Household",
    village: "Ramnagar Sub-Center",
    district: "Sitapur",
    state: "Uttar Pradesh",
    headOfHousehold: "Ram Prasad Devi",
    rationCategory: "AAY (Antyodaya)",
    members: [
      {
        id: "mem-sunita",
        name: "Sunita Devi",
        relation: "Spouse",
        age: 24,
        gender: "Female",
        village: "Ramnagar",
        district: "Sitapur",
        state: "Uttar Pradesh",
        aadhaarNumber: "6621 8839 0192",
        rationCardNumber: "UP-SIT-AAY-49102",
        annualIncome: 42000,
        healthConditions: ["Pregnant (32 Weeks / 3rd Trimester)", "High-Risk Pregnancy Flag"],
        documents: [],
      },
    ],
  },
];

export const DEMO_SCHEMES: GovernmentScheme[] = [
  {
    id: "scheme-pmjay",
    code: "PM-JAY",
    name: "Ayushman Bharat PM-JAY",
    department: "National Health Authority (Govt of India)",
    stateScope: "Pan-India",
    coverageAmount: "₹ 5,00,000 / family / year",
    description: "World's largest public health assurance scheme providing secondary and tertiary care hospitalization to over 12 crore poor and vulnerable families.",
    eligibilityCriteria: [
      "Deprivation criteria based on SECC 2011 rural database",
      "Active Antyodaya Anna Yojana (AAY) or BPL Ration card",
      "Family linked with biometric Aadhaar",
    ],
    requiredDocs: ["Aadhaar Card", "Ration Card (BPL)", "Valid Income Certificate"],
    directBenefit: "Cashless in-patient hospital treatments across 28,000+ empaneled government & private hospitals.",
  },
  {
    id: "scheme-arogya-ka",
    code: "AB-ArK",
    name: "Arogya Karnataka (Ayushman Bharat - ArK)",
    department: "Dept of Health & Family Welfare, Govt of Karnataka",
    stateScope: "Karnataka",
    coverageAmount: "₹ 5,00,000 (Eligible) / 30% Concession (General)",
    description: "State-integrated scheme guaranteeing universal health coverage for all residents of Karnataka through PHC referral networks.",
    eligibilityCriteria: [
      "Resident of Karnataka with food security BPL card",
      "Aadhaar biometric authentication",
      "PHC/CHC medical officer referral for tertiary treatments",
    ],
    requiredDocs: ["Aadhaar Card", "Karnataka Ration Card", "PHC Referral Slip"],
    directBenefit: "Covers 1,650 complex surgical and medical procedures without any out-of-pocket costs.",
  },
  {
    id: "scheme-jsy",
    code: "JSY",
    name: "Janani Suraksha Yojana (JSY)",
    department: "National Health Mission (NHM)",
    stateScope: "Pan-India",
    coverageAmount: "₹ 1,400 Rural Cash Incentive + Free Transport",
    description: "Safe motherhood intervention promoting institutional delivery among poor pregnant women, dramatically reducing maternal and neonatal mortality.",
    eligibilityCriteria: [
      "Pregnant woman registered with local ASHA / ANM",
      "Delivery conducted at an accredited government PHC / CHC / Hospital",
      "Mother and Child Protection (MCP) card issued",
    ],
    requiredDocs: ["Aadhaar Card", "MCP Card", "Bank Passbook linked to Aadhaar"],
    directBenefit: "Direct Benefit Transfer (DBT) cash assistance plus free diet, free diagnostics, and free drop-back ambulance.",
  },
  {
    id: "scheme-cmchis-tn",
    code: "CMCHIS",
    name: "Chief Minister's Comprehensive Health Insurance Scheme",
    department: "Govt of Tamil Nadu",
    stateScope: "Tamil Nadu",
    coverageAmount: "₹ 5,00,000 / family / year",
    description: "State health insurance scheme covering 1,090 surgical procedures and 154 specialized day-care packages.",
    eligibilityCriteria: [
      "Annual family income below ₹1,20,000",
      "Tamil Nadu Family Smart Card (Ration Card)",
    ],
    requiredDocs: ["Aadhaar Card", "Smart Ration Card", "Village Administrative Officer (VAO) Income Slip"],
    directBenefit: "Completely cashless coverage across empaneled hospitals in Tamil Nadu.",
  },
];

export const DEMO_FACILITIES: HealthcareFacility[] = [
  {
    id: "fac-keragodu-phc",
    name: "Keragodu Primary Health Center (PHC)",
    type: "PHC",
    distanceKm: 3.2,
    travelTimeMin: 7,
    phone: "+91 8232 248102",
    location: "Main Road, Keragodu Gram Panchayat, Mandya",
    doctorOnDuty: "Dr. Anita Rao, MBBS (Medical Officer)",
    emergencyBeds: 6,
    oxygenCylinders: 4,
    antivenomStock: 12,
    bloodUnitsStock: 0,
    is24x7: false,
  },
  {
    id: "fac-mandya-chc",
    name: "Mandya Taluk Community Health Center (CHC)",
    type: "CHC",
    distanceKm: 9.8,
    travelTimeMin: 18,
    phone: "+91 8232 229105",
    location: "Near Bus Terminal, Mandya Taluk",
    doctorOnDuty: "Dr. K. Venkatesh, MD (Physician on Call)",
    emergencyBeds: 24,
    oxygenCylinders: 18,
    antivenomStock: 35,
    bloodUnitsStock: 14,
    is24x7: true,
  },
  {
    id: "fac-mandya-dh",
    name: "Mandya District Civil Hospital & Trauma Center",
    type: "District Hospital",
    distanceKm: 18.5,
    travelTimeMin: 32,
    phone: "+91 8232 220044",
    location: "BIMS Campus, Hospital Road, Mandya City",
    doctorOnDuty: "Dr. Suresh Patil (Emergency HOD) + 4 Duty Surgeons",
    emergencyBeds: 110,
    oxygenCylinders: 85,
    antivenomStock: 80,
    bloodUnitsStock: 65,
    is24x7: true,
  },
];

export const DEMO_HEALTH_TWINS: Record<string, HealthTwinMetrics> = {
  "mem-ramesh": {
    memberId: "mem-ramesh",
    memberName: "Ramesh Gowda",
    age: 48,
    gender: "Male",
    bloodGroup: "O+",
    vitals: {
      bpSystolic: 138,
      bpDiastolic: 88,
      pulseRate: 76,
      bloodSugar: 128,
      spo2: 98,
      temperatureF: 98.4,
      bmi: 24.2,
    },
    chronicRiskScores: {
      cardiovascular: "Moderate",
      respiratory: "Low",
      diabetes: "Moderate",
    },
    clinicalAlerts: [
      {
        title: "Pre-Hypertension Warning (138/88 mmHg)",
        description: "Blood pressure reading is borderline elevated across the last 3 ASHA home visits. Dietary sodium reduction recommended.",
        severity: "yellow",
        action: "Schedule routine blood pressure check at Keragodu PHC next Tuesday.",
      },
      {
        title: "Random Blood Sugar Watch (128 mg/dL)",
        description: "Post-meal glucose shows slight insulin resistance. Recommended fasting blood glucose check at PHC lab.",
        severity: "yellow",
        action: "Follow up with ASHA worker for fasting glucometer strip test.",
      },
    ],
    immunizations: [
      { vaccine: "Tetanus Toxoid (TT)", status: "Completed", dateOrDue: "14/06/2024" },
      { vaccine: "COVID-19 Booster", status: "Completed", dateOrDue: "20/09/2022" },
      { vaccine: "Annual Influenza (Seasonal)", status: "Due Soon", dateOrDue: "Next Month" },
    ],
  },
  "mem-sunita": {
    memberId: "mem-sunita",
    memberName: "Sunita Devi",
    age: 24,
    gender: "Female",
    bloodGroup: "B+",
    vitals: {
      bpSystolic: 148,
      bpDiastolic: 96,
      pulseRate: 92,
      bloodSugar: 104,
      spo2: 97,
      temperatureF: 98.6,
      bmi: 22.8,
    },
    chronicRiskScores: {
      cardiovascular: "Moderate",
      respiratory: "Low",
      diabetes: "Low",
      maternal: "Critical",
    },
    clinicalAlerts: [
      {
        title: "HIGH-RISK PREGNANCY RED FLAG — Preeclampsia Warning",
        description: "Blood pressure 148/96 mmHg at 32 weeks gestation with reported ankle swelling and persistent frontal headache.",
        severity: "red",
        action: "Immediate institutional redirection required! Do not wait for routine OPD. Escort to CHC/District Hospital with Obstetrician on duty.",
      },
    ],
    immunizations: [
      { vaccine: "Td 1 (Tetanus & Diphtheria)", status: "Completed", dateOrDue: "10/04/2026" },
      { vaccine: "Td 2 Booster", status: "Completed", dateOrDue: "08/05/2026" },
      { vaccine: "Calcium & Iron Folic Acid (IFA)", status: "Completed", dateOrDue: "Daily Course Active" },
    ],
  },
};
